# Generated by Django 2.0.1 on 2018-02-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.TextField(max_length=255)),
                ('location', models.TextField(max_length=255)),
                ('degree', models.TextField(max_length=255)),
                ('major', models.TextField(max_length=255)),
                ('gpa', models.FloatField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('location', models.TextField(max_length=255)),
                ('start_date', models.DateField(max_length=255)),
                ('end_date', models.DateField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
    ]
