# Generated by Django 2.0.1 on 2018-02-20 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='full_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.resume'),
        ),
    ]
